#!/bin/sh
#compile the file
gcc -std=c99 $1.c

# UNIX timestamp concatenated with nanoseconds
T="$(date +%s%N)"

# Run the executable
./a.exe

# Time interval in nanoseconds
T="$(($(date +%s%N)-T))"
# Seconds
S="$((T/1000000000))"
# Milliseconds
M="$((T/1000000))"

#echo "Time in nanoseconds: ${T}"
printf "**Runtime: %02d:%02d:%02d.%03d **\n" "$((S/3600%24))" "$((S/60%60))" "$((S%60))" "${M}"

